[package]
name = "jsoncpl"
version = "0.2.5"
edition = "2021"
authors = [ "Leon Camus" ]

[dependencies]
nom = "7.1"
nom_locate = "4.0"
human-sort = "0.2"
similar = "2.1"
colour = "0.6"
clap = { version = "3.1", features = ["derive"] }
pathdiff = "0.2"
unescape = "0.1"

[dev-dependencies]
indexmap = "1.8"
serde_json = { version = "1.0", features = ["preserve_order"] }

[profile.release]
lto = true
debug = false
codegen-units = 1
panic = "abort"
